#include <mission/gameplaymanager.cpp>
#include <mission/haspresentationinfo.cpp>
#include <mission/mission.cpp>
#include <mission/missionmanager.cpp>
#include <mission/missionscriptloader.cpp>
#include <mission/missionstage.cpp>
#include <mission/animatedicon.cpp>
#include <mission/bonusmissioninfo.cpp>
#include <mission/nocopbonusobjective.cpp>
#include <mission/nodamagebonusobjective.cpp>
#include <mission/timeremainbonusobjective.cpp>
#include <mission/racepositionbonusobjective.cpp>
#include <mission/statepropcollectible.cpp>