const char* ERROR_STRINGS[] =
{
//English
    "Success",
    "FILE NOT FOUND",
    "The disc tray is open",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "No disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
    "Incorrect disc. \nInsert The Simpsons Hit & Run disc.",
//French
    "Success",
    "FILE NOT FOUND",
    "Le compartiment à disque est ouvert.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Aucun disque.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
    "Disque incorrect.\nInsérez le disque The Simpsons Hit & Run.",
//German
    "Success",
    "FILE NOT FOUND",
    "Die DVD/CD - Lade ist geöffnet",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Keine DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
    "Falsche DVD/CD-ROM. Leg die\nTHE SIMPSONS Hit & Run-DVD/CD-ROM ein.",
//Spanish
    "Success",
    "FILE NOT FOUND",
    "La bandeja del disco está abierta.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "No se ha introducido ningún disco.\nInserta el disco de Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",
    "Disco incorrecto.\nInserta el disco de The Simpsons Hit & Run.",

    "" // dummy terminator

};
