const char* ERROR_STRINGS[] =
{
//English
    "Success",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "The Disc Tray is open.\nIf you want to continue the game,\nplease close the Disc Tray.",
    "This is not \nThe Simpsons Hit & Run\nGame Disc.  Please insert\nThe Simpsons Hit & Run\nGame Disc.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
    "There is a problem with\nthe disc you're using.\nIt may be dirty or damaged.",
//French
    "Success",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "",
    "",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
    "Le disque utilisé présente une anomalie.\nIl est peut-être sale ou endommagé.",
//German
    "Success",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "",
    "",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
    "Problem bei der benutzten CD:\nCD ist verschmutzt oder beschädigt.",
//Spanish
    "Success",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "",
    "",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",
    "Hay un problema con el disco que estás usando.\nPuede estar sucio o dañado.",

    "" // dummy terminator

};
