#include <camera/animatedcam.cpp>
#include <camera/bumpercam.cpp>
#include <camera/chasecam.cpp>
#include <camera/conversationcam.cpp>
#include <camera/debugcam.cpp>
#include <camera/followcam.cpp>
#include <camera/kullcam.cpp>
#include <camera/relativeanimatedcam.cpp>
#include <camera/railcam.cpp>
#include <camera/sinecosshaker.cpp>
#include <camera/supercam.cpp>
#include <camera/supercamcentral.cpp>
#include <camera/supercamcontroller.cpp>
#include <camera/supercammanager.cpp>
#include <camera/trackercam.cpp>
#include <camera/walkercam.cpp> 
#include <camera/wrecklesscam.cpp>
#include <camera/wrecklesseventlistener.cpp>
#include <camera/staticcam.cpp>
#include <camera/reversecam.cpp>
#include <camera/surveillancecam.cpp>
#include <camera/supersprintcam.cpp>
//#include <camera/firstpersoncam.cpp>