#include <mission/objectives/deliveryobjective.cpp>
#include <mission/objectives/destroyobjective.cpp>
#include <mission/objectives/destroybossobjective.cpp>
#include <mission/objectives/dialogueobjective.cpp>
#include <mission/objectives/followobjective.cpp>
#include <mission/objectives/getinobjective.cpp>
#include <mission/objectives/gotoobjective.cpp>
#include <mission/objectives/loseobjective.cpp>
#include <mission/objectives/missionobjective.cpp>
#include <mission/objectives/raceobjective.cpp>
#include <mission/objectives/talktoobjective.cpp>
#include <mission/objectives/collectibleobjective.cpp>
#include <mission/objectives/collectdumpedobjective.cpp>
#include <mission/objectives/fmvobjective.cpp>
#include <mission/objectives/interiorobjective.cpp>
#include <mission/objectives/coinobjective.cpp>
#include <mission/objectives/loadvehicleobjective.cpp>
#include <mission/objectives/pickupitemobjective.cpp>
#include <mission/objectives/timerobjective.cpp>
#include <mission/objectives/buycarobjective.cpp>
#include <mission/objectives/buyskinobjective.cpp>
#include <mission/objectives/gooutsideobjective.cpp>