#include <sound/movingpositional/movingsoundmanager.cpp>
#include <sound/movingpositional/vehicleposnsoundplayer.cpp>
#include <sound/movingpositional/aivehiclesoundplayer.cpp>
#include <sound/movingpositional/trafficsoundplayer.cpp>
#include <sound/movingpositional/avatarvehicleposnplayer.cpp>
#include <sound/movingpositional/actorplayer.cpp>
#include <sound/movingpositional/waspsoundplayer.cpp>
#include <sound/movingpositional/platformsoundplayer.cpp>
#include <sound/movingpositional/animobjsoundplayer.cpp>