#include <render/Loaders/AllWrappers.cpp>
#include <render/Loaders/AnimCollLoader.cpp>
#include <render/Loaders/AnimDSGLoader.cpp>
#include <render/Loaders/BillboardWrappedLoader.cpp>
#include <render/Loaders/breakableobjectloader.cpp>
#include <render/Loaders/DynaPhysLoader.cpp>
#include <render/Loaders/FenceLoader.cpp>
#include <render/Loaders/GeometryWrappedLoader.cpp>
#include <render/Loaders/instparticlesystemloader.cpp>
#include <render/Loaders/InstStatEntityLoader.cpp>
#include <render/Loaders/InstStatPhysLoader.cpp>
#include <render/Loaders/IntersectLoader.cpp>
#include <render/Loaders/StaticEntityLoader.cpp>
#include <render/Loaders/StaticPhysLoader.cpp>
#include <render/Loaders/TreeDSGLoader.cpp>
#include <render/Loaders/WorldSphereLoader.cpp>
#include <render/Loaders/LensFlareLoader.cpp>
#include <render/Loaders/AnimDynaPhysLoader.cpp>