#include <ai/actor/actormanager.cpp>
#include <ai/actor/flyingactor.cpp>
#include <ai/actor/actor.cpp>
#include <ai/actor/attackbehaviour.cpp>
#include <ai/actor/evasionbehaviour.cpp>
#include <ai/actor/spawnpoint.cpp>
#include <ai/actor/projectile.cpp>
#include <ai/actor/actordsg.cpp>
#include <ai/actor/ufoattackbehaviour.cpp>
#include <ai/actor/actoranimationwasp.cpp>
#include <ai/actor/actoranimationufo.cpp>
#include <ai/actor/attractionbehaviour.cpp>
#include <ai/actor/projectiledsg.cpp>
#include <ai/actor/ufobeamalwaysonbehaviour.cpp>
#include <ai/actor/ufobehaviour.cpp>
#include <ai/actor/intersectionlist.cpp>