#include <presentation/gui/ingame/guimanageringame.cpp>
#include <presentation/gui/ingame/guiscreenhastransitions.cpp>
#include <presentation/gui/ingame/guiscreenhud.cpp>
#include <presentation/gui/ingame/guiscreeniriswipe.cpp>
#include <presentation/gui/ingame/guiscreenlevelstats.cpp>
#include <presentation/gui/ingame/guiscreenlevelend.cpp>
#include <presentation/gui/ingame/guiscreenletterbox.cpp>
#include <presentation/gui/ingame/guiscreenmissionbase.cpp>
#include <presentation/gui/ingame/guiscreenmissionload.cpp>
#include <presentation/gui/ingame/guiscreenmissionover.cpp>
#include <presentation/gui/ingame/guiscreenmissionsuccess.cpp>
#include <presentation/gui/ingame/guiscreenmultihud.cpp>
#include <presentation/gui/ingame/guiscreenpause.cpp>
#include <presentation/gui/ingame/guiscreenpausemission.cpp>
#include <presentation/gui/ingame/guiscreenpauseoptions.cpp>
#include <presentation/gui/ingame/guiscreenpausecontroller.cpp>
#include <presentation/gui/ingame/guiscreenpausesound.cpp>
#include <presentation/gui/ingame/guiscreenpausesettings.cpp>
#include <presentation/gui/ingame/guiscreenpausesunday.cpp>
#include <presentation/gui/ingame/guiscreenrewards.cpp>
#include <presentation/gui/ingame/guiscreenphonebooth.cpp>
#include <presentation/gui/ingame/guiscreenpurchaserewards.cpp>
#include <presentation/gui/ingame/guiscreenmissionselect.cpp>
#include <presentation/gui/ingame/guiscreensavegame.cpp>
#include <presentation/gui/ingame/guiscreenviewcards.cpp>
#include <presentation/gui/ingame/guiscreentutorial.cpp>
#include <presentation/gui/ingame/guiscreencreditspostfmv.cpp>
