#include <sound/dialog/conversation.cpp>
#include <sound/dialog/conversationmatcher.cpp>
#include <sound/dialog/dialogcoordinator.cpp>
#include <sound/dialog/dialogline.cpp>
#include <sound/dialog/dialoglist.cpp>
#include <sound/dialog/dialogpriorityqueue.cpp>
#include <sound/dialog/dialogqueueelement.cpp>
#include <sound/dialog/dialogselectiongroup.cpp>
#include <sound/dialog/playabledialog.cpp>
#include <sound/dialog/selectabledialog.cpp>
#include <sound/dialog/dialogsounddebugpage.cpp>
