#include <presentation/gui/frontend/guimanagerfrontend.cpp>
#include <presentation/gui/frontend/guiscreencardgallery.cpp>
#include <presentation/gui/frontend/guiscreencontroller.cpp>
#include <presentation/gui/frontend/guiscreenloadgame.cpp>
#include <presentation/gui/frontend/guiscreenmainmenu.cpp>
#include <presentation/gui/frontend/guiscreenmissiongallery.cpp>
#include <presentation/gui/frontend/guiscreenskingallery.cpp>
#include <presentation/gui/frontend/guiscreenvehiclegallery.cpp>
//#include <presentation/gui/frontend/guiscreenmultichoosechar.cpp>
//#include <presentation/gui/frontend/guiscreenmultisetup.cpp>
#include <presentation/gui/frontend/guiscreenoptions.cpp>
#include <presentation/gui/frontend/guiscreenplaymovie.cpp>
#include <presentation/gui/frontend/guiscreenscrapbook.cpp>
#include <presentation/gui/frontend/guiscreenscrapbookcontents.cpp>
#include <presentation/gui/frontend/guiscreenscrapbookstats.cpp>
#include <presentation/gui/frontend/guiscreensound.cpp>
#include <presentation/gui/frontend/guiscreensplash.cpp>
#include <presentation/gui/frontend/guiscreenviewcredits.cpp>
#include <presentation/gui/frontend/guiscreenviewmovies.cpp>
